---
- name: Install system packages
  apt:
    pkg:
      - lsof
      - telnet
      - make
      - psmisc
      - traceroute
      - bind9-dnsutils
      - jq
      - util-linux
      - bsdmainutils
      - awscli
      - curl
      - wget
      - git
      - vim
      - apache2-utils
      - mc
      - lnav
      - htop
      - iftop
      - iotop
      - unzip
      - python3-pymysql
      - python3-boto3
      - python3-passlib
      - python3-psycopg2
      - mysql-client
      - postgresql-client
      - gnupg2
      - ca-certificates
      - apt-transport-https
      - dirmngr
      - python-apt
      - acl
      - locales
      - gpg-agent
    update_cache: true
